[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",  # Docstrings
    "C408",  # "Unnecessary {obj_type} call (rewrite as a literal)", dict() is more readable in many case
    "T201",  # "print found" is not an issue for scripts
    "INP001",  # File {filename} is part of an implicit namespace package. Add an __init__.py.
    "S324",  # Probable use of insecure hash functions in `hashlib`: `md5`
    # Ignored because of "warning: The following rules may cause conflicts when used with the formatter"
    "COM812",  # Trailing comma missing
    "ISC001",  # Implicitly concatenated string literals on one line
    "S603", # `subprocess` call: check for execution of untrusted input
    "S607", # Starting a process with a partial executable path
]